/**
 * Des lignes d'ingrédients réelles, relevées le 08/10/2026 sur Marmiton et
 * CuisineAZ (une douzaine de recettes) : le corpus sur lequel l'analyseur est
 * éprouvé (`ingredients.test.ts`). Telles quelles, fautes et « (s) » compris.
 */
export const REAL_INGREDIENT_LINES: readonly string[] = [
  "1 pâte brisée",
  "6 pommes Golden",
  "1 sachet de sucre vanillé",
  "30 g de beurre",
  "300 g de farine",
  "3 oeufs entiers",
  "3 cuillères à soupe de sucre",
  "2 cuillères à soupe d'huile",
  "50 g de beurre fondu",
  "60 cl de lait",
  "5 cl de rhum",
  "4 Pain complet",
  "4 tranche(s) Jambon cru",
  "80 g Fromage frais",
  "4 Radis",
  "Ciboulette",
  "Persil",
  "200 g de pâtes brisées",
  "200 g de lardons",
  "3 oeufs",
  "20 cl de crème fraîche",
  "20 cl de lait",
  "muscade",
  "sel",
  "poivre",
  "Préparation",
  "7 Œuf(s) entier(s)",
  "1 boîte(s) Thon",
  "150 g Surimi(s)",
  "1 boîte(s) Concentré de tomate",
  "1 brique(s) Crème fraîche liquide 30% de matière grasse",
  "1 pincée(s) Piment de cayenne",
  "Sel poivre",
  "350 g d'aubergines",
  "350 g de courgettes",
  "350 g de poivrons de couleur rouge et vert",
  "350 g d'oignons",
  "500 g de tomates bien mûres",
  "3 gousses d'ail",
  "6 cuillères à soupe d'huile d'olive",
  "1 brin de thym",
  "1 feuille de laurier",
  "200 g de chocolat pâtissier",
  "100 g de beurre + une noix pour le moule",
  "50 g de farine",
  "100 g de sucre en poudre",
  "1 paquet de lasagnes",
  "3 oignons jaunes",
  "2 gousses d'ail",
  "1 branche de céleri",
  "1 carotte",
  "600 g de boeuf haché",
  "800 g de purée de tomate",
  "15 cl d'eau",
  "20 cl de vin rouge",
  "2 feuilles de laurier",
  "thym",
  "basilic",
  "3 pincées de muscade râpée",
  "70 g de fromage râpé",
  "125 g de parmesan",
  "100 g de farine",
  "125 g de beurre",
  "1 l de lait",
  "20 Spéculoos",
  "1 Œuf(s)",
  "100 g Beurre",
  "170 g Farine",
  "200 g Chocolat noir dessert",
  "200 ml Crème liquide entière",
  "2 courgettes",
  "1 oignon",
  "1 aubergine",
  "35 cl de lait",
  "1 oeuf",
  "50 g de gruyère râpé",
  "50 g de flocons d'avoine",
  "600 g de bourguignon",
  "4 oignons",
  "4 carottes",
  "1 bouquet garni",
  "1 bouteille de vin rouge assez bon",
  "100 g de beurre",
  "4 oeufs",
  "160 g de chocolat noir",
  "160 g de beurre",
  "160 g de sucre",
  "40 g de farine",
  "1 pincée de sel",
];
